import 'package:flutter/material.dart';

import '../models/grocery_item.dart';
import '../models/meal_plan.dart';
import '../models/recipe.dart';
import '../services/grocery_service.dart';
import '../services/meal_plan_service.dart';
import '../services/recipe_service.dart';
import 'weekly_planner_page.dart' show kDays, kMealTypes;

class GroceryListPage extends StatefulWidget {
  const GroceryListPage({super.key});

  @override
  State<GroceryListPage> createState() => _GroceryListPageState();
}

class _GroceryListPageState extends State<GroceryListPage> {
  List<GroceryItem> _items = [];
  final Set<int> _selectedWeeks = {};

  @override
  void initState() {
    super.initState();
    _refresh();
  }

  void _refresh() {
    setState(() {
      _items = GroceryService.getAllItems();
    });
  }

  // ── Generate ──────────────────────────────────────────────────────────────

  Future<void> _generate() async {
    if (_selectedWeeks.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Select at least one week first')),
      );
      return;
    }

    // Clear auto-generated items before re-generating
    await GroceryService.clearAutoGenerated();

    // Accumulate (name_lower, unit) -> total quantity
    final Map<String, _AccumItem> accum = {};

    for (final week in _selectedWeeks) {
      final plans = MealPlanService.getMealPlansForWeek(week);
      for (final MealPlan plan in plans) {
        if (plan.recipeId == null) continue;
        final Recipe? recipe = RecipeService.getRecipeById(plan.recipeId!);
        if (recipe == null) continue;

        for (final ing in recipe.ingredients) {
          final key = '${ing.name.toLowerCase()}|||${ing.unit}';
          if (accum.containsKey(key)) {
            accum[key]!.quantity += ing.quantity;
          } else {
            accum[key] = _AccumItem(
              name: ing.name,
              unit: ing.unit,
              quantity: ing.quantity,
              category: categorizeIngredient(ing.name),
            );
          }
        }
      }
    }

    if (accum.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
            content:
                Text('No meals planned for the selected weeks yet.')),
      );
      return;
    }

    int _idSeq = 0;
    for (final item in accum.values) {
      final gi = GroceryItem(
        id: '${DateTime.now().millisecondsSinceEpoch}_${_idSeq++}',
        name: item.name,
        category: item.category,
        quantity: item.quantity,
        unit: item.unit,
        isManual: false,
      );
      await GroceryService.saveItem(gi);
    }

    _refresh();

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
            content: Text(
                'Generated ${accum.length} items from '
                '${_selectedWeeks.length} week(s)')),
      );
    }
  }

  // ── Manual add ───────────────────────────────────────────────────────────

  Future<void> _showAddItemDialog() async {
    final nameCtrl = TextEditingController();
    String category = kGroceryCategories.first;

    await showDialog<void>(
      context: context,
      builder: (ctx) {
        return StatefulBuilder(builder: (ctx, setSt) {
          return AlertDialog(
            title: const Text('Add Item'),
            content: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  TextField(
                    controller: nameCtrl,
                    textCapitalization: TextCapitalization.words,
                    decoration: const InputDecoration(
                      labelText: 'Item Name *',
                      border: OutlineInputBorder(),
                    ),
                  ),
                  const SizedBox(height: 12),
                  DropdownButtonFormField<String>(
                    value: category,
                    decoration: const InputDecoration(
                      labelText: 'Category',
                      border: OutlineInputBorder(),
                    ),
                    items: kGroceryCategories
                        .map((c) =>
                            DropdownMenuItem(value: c, child: Text(c)))
                        .toList(),
                    onChanged: (v) {
                      if (v != null) setSt(() => category = v);
                    },
                  ),
                ],
              ),
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(ctx),
                child: const Text('Cancel'),
              ),
              FilledButton(
                onPressed: () async {
                  final name = nameCtrl.text.trim();
                  if (name.isEmpty) return;
                  final item = GroceryItem(
                    id: DateTime.now().microsecondsSinceEpoch.toString(),
                    name: name,
                    category: category,
                    isManual: true,
                  );
                  await GroceryService.saveItem(item);
                  if (ctx.mounted) Navigator.pop(ctx);
                  _refresh();
                },
                child: const Text('Add'),
              ),
            ],
          );
        });
      },
    );
  }

  // ── Clear options ─────────────────────────────────────────────────────────

  Future<void> _clearChecked() async {
    await GroceryService.deleteChecked();
    _refresh();
  }

  Future<void> _clearAll() async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Clear All?'),
        content: const Text('Remove all grocery items?'),
        actions: [
          TextButton(
              onPressed: () => Navigator.pop(ctx, false),
              child: const Text('Cancel')),
          FilledButton(
              onPressed: () => Navigator.pop(ctx, true),
              child: const Text('Clear All')),
        ],
      ),
    );
    if (confirmed == true) {
      await GroceryService.clearAll();
      _refresh();
    }
  }

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;

    // Group items by category in store order
    final Map<String, List<GroceryItem>> grouped = {};
    for (final cat in kGroceryCategories) {
      grouped[cat] = [];
    }
    for (final item in _items) {
      final cat = kGroceryCategories.contains(item.category)
          ? item.category
          : 'Other';
      grouped[cat]!.add(item);
    }

    final usedCategories = kGroceryCategories
        .where((c) => grouped[c]!.isNotEmpty)
        .toList();

    return Scaffold(
      appBar: AppBar(
        title: const Text('Grocery List'),
        backgroundColor: cs.primaryContainer,
        foregroundColor: cs.onPrimaryContainer,
        actions: [
          PopupMenuButton<String>(
            onSelected: (v) {
              if (v == 'clear_checked') _clearChecked();
              if (v == 'clear_all') _clearAll();
            },
            itemBuilder: (_) => [
              const PopupMenuItem(
                  value: 'clear_checked',
                  child: Text('Clear Purchased Items')),
              const PopupMenuItem(
                  value: 'clear_all', child: Text('Clear All')),
            ],
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _showAddItemDialog,
        icon: const Icon(Icons.add),
        label: const Text('Add Item'),
      ),
      body: Column(
        children: [
          // Week selectors + generate button
          Padding(
            padding: const EdgeInsets.all(8),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Generate from week(s):',
                    style: Theme.of(context).textTheme.labelLarge),
                const SizedBox(height: 6),
                Row(
                  children: [
                    ...List.generate(4, (i) {
                      final w = i + 1;
                      return Padding(
                        padding: const EdgeInsets.only(right: 6),
                        child: FilterChip(
                          label: Text('Week $w'),
                          selected: _selectedWeeks.contains(w),
                          onSelected: (sel) {
                            setState(() {
                              if (sel) {
                                _selectedWeeks.add(w);
                              } else {
                                _selectedWeeks.remove(w);
                              }
                            });
                          },
                        ),
                      );
                    }),
                    const Spacer(),
                    FilledButton.icon(
                      onPressed: _generate,
                      icon: const Icon(Icons.auto_awesome, size: 16),
                      label: const Text('Generate'),
                    ),
                  ],
                ),
              ],
            ),
          ),
          const Divider(height: 1),
          // List
          Expanded(
            child: _items.isEmpty
                ? const Center(
                    child: Text(
                      'No items yet.\nGenerate from your weekly plan\nor add manually.',
                      textAlign: TextAlign.center,
                      style: TextStyle(fontSize: 16, color: Colors.grey),
                    ),
                  )
                : ListView.builder(
                    padding: const EdgeInsets.only(bottom: 100),
                    itemCount: usedCategories.length,
                    itemBuilder: (_, ci) {
                      final cat = usedCategories[ci];
                      final catItems = grouped[cat]!;
                      return Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Padding(
                            padding: const EdgeInsets.fromLTRB(16, 12, 16, 4),
                            child: Text(
                              cat,
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 13,
                                color: cs.primary,
                              ),
                            ),
                          ),
                          ...catItems.map((item) => CheckboxListTile(
                                value: item.isChecked,
                                onChanged: (_) async {
                                  await GroceryService.toggleChecked(item.id);
                                  _refresh();
                                },
                                title: Text(
                                  item.name,
                                  style: TextStyle(
                                    decoration: item.isChecked
                                        ? TextDecoration.lineThrough
                                        : null,
                                    color: item.isChecked
                                        ? Colors.grey
                                        : null,
                                  ),
                                ),
                                subtitle: item.quantity != null
                                    ? Text(
                                        '${_fmtQty(item.quantity!)} ${item.unit ?? ''}')
                                    : null,
                                secondary: item.isManual
                                    ? const Icon(Icons.edit_note,
                                        size: 16, color: Colors.grey)
                                    : null,
                                dense: true,
                              )),
                          const Divider(height: 1),
                        ],
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }

  String _fmtQty(double q) {
    if (q == q.truncateToDouble()) return q.toInt().toString();
    return q.toStringAsFixed(2);
  }
}

// ─── Helper data class ────────────────────────────────────────────────────────

class _AccumItem {
  final String name;
  final String unit;
  double quantity;
  final String category;

  _AccumItem({
    required this.name,
    required this.unit,
    required this.quantity,
    required this.category,
  });
}
