import 'package:hive_flutter/hive_flutter.dart';

import '../models/grocery_item.dart';

/// Manages grocery list persistence using Hive.
class GroceryService {
  static const String _boxName = 'grocery_items';

  GroceryService._();

  static Box<String>? _box;

  static Future<void> init() async {
    _box = Hive.box<String>(_boxName);
  }

  static Box<String> get _openBox {
    assert(_box != null && _box!.isOpen,
        'GroceryService.init() must be called before use.');
    return _box!;
  }

  static List<GroceryItem> getAllItems() {
    return _openBox.values.map((json) => GroceryItem.fromJson(json)).toList();
  }

  static Future<void> saveItem(GroceryItem item) async {
    await _openBox.put(item.id, item.toJson());
  }

  static Future<void> deleteItem(String id) async {
    await _openBox.delete(id);
  }

  static Future<void> clearAll() async {
    await _openBox.clear();
  }

  /// Clears only auto-generated (non-manual) items.
  static Future<void> clearAutoGenerated() async {
    final autoKeys = getAllItems()
        .where((item) => !item.isManual)
        .map((item) => item.id)
        .toList();
    await _openBox.deleteAll(autoKeys);
  }

  static Future<void> toggleChecked(String id) async {
    final json = _openBox.get(id);
    if (json == null) return;
    final item = GroceryItem.fromJson(json);
    item.isChecked = !item.isChecked;
    await _openBox.put(id, item.toJson());
  }

  static Future<void> deleteChecked() async {
    final checkedKeys = getAllItems()
        .where((item) => item.isChecked)
        .map((item) => item.id)
        .toList();
    await _openBox.deleteAll(checkedKeys);
  }
}
