import '../models/recipe.dart';

/// Provides the initial set of 27 seed recipes for the app.
class RecipeSeed {
  RecipeSeed._();

  /// Returns all 27 seed recipes with full ingredient and nutrition data.
  static List<Recipe> getSeedRecipes() {
    return [
      // ─── Breakfast ────────────────────────────────────────────────────────
      Recipe(
        id: 'seed_001',
        name: 'Scrambled Eggs',
        category: 'Breakfast',
        mealType: 'Breakfast',
        ingredients: [
          RecipeIngredient(quantity: 2, unit: 'large', name: 'Egg'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Egg Whites'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Frozen Spinach'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Bell Peppers'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Avocado'),
        ],
        totalCalories: 290,
        macros: Macros(protein: 22, carbs: 9, fat: 19),
      ),
      Recipe(
        id: 'seed_002',
        name: 'Picante Eggs',
        category: 'Breakfast',
        mealType: 'Breakfast',
        ingredients: [
          RecipeIngredient(quantity: 2, unit: 'large', name: 'Egg'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Egg Whites'),
          RecipeIngredient(quantity: 0.25, unit: 'cup', name: 'Salsa'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Avocado'),
        ],
        totalCalories: 245,
        macros: Macros(protein: 19, carbs: 9, fat: 15),
      ),
      Recipe(
        id: 'seed_003',
        name: 'Hard Boiled Eggs + Avocado',
        category: 'Breakfast',
        mealType: 'Breakfast',
        ingredients: [
          RecipeIngredient(quantity: 2, unit: 'large', name: 'Hard Boiled Eggs'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Avocado'),
        ],
        totalCalories: 265,
        macros: Macros(protein: 14, carbs: 6, fat: 20),
      ),
      Recipe(
        id: 'seed_004',
        name: 'Veggie Omelette',
        category: 'Breakfast',
        mealType: 'Breakfast',
        ingredients: [
          RecipeIngredient(quantity: 2, unit: 'large', name: 'Egg'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Egg Whites'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Bell Peppers'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Frozen Spinach'),
          RecipeIngredient(quantity: 0.25, unit: 'cup', name: 'Onion'),
        ],
        totalCalories: 230,
        macros: Macros(protein: 20, carbs: 8, fat: 13),
      ),
      Recipe(
        id: 'seed_005',
        name: 'Protein Smoothie',
        category: 'Breakfast',
        mealType: 'Breakfast',
        ingredients: [
          RecipeIngredient(quantity: 1, unit: 'scoop', name: 'Protein Powder'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Almond Milk'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Frozen Spinach'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Avocado'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Raspberry'),
        ],
        totalCalories: 310,
        macros: Macros(protein: 28, carbs: 24, fat: 10),
      ),

      // ─── Main ─────────────────────────────────────────────────────────────
      Recipe(
        id: 'seed_006',
        name: 'Stuffed Peppers',
        category: 'Main',
        mealType: 'Dinner',
        ingredients: [
          RecipeIngredient(quantity: 4, unit: 'oz', name: 'Ground Turkey'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Onion'),
          RecipeIngredient(quantity: 1, unit: 'large', name: 'Bell Peppers'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Tomato Sauce'),
          RecipeIngredient(quantity: 2, unit: 'cloves', name: 'Garlic'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Cherry Tomato'),
        ],
        totalCalories: 355,
        macros: Macros(protein: 30, carbs: 26, fat: 12),
      ),
      Recipe(
        id: 'seed_007',
        name: 'Taco Rice W/Beef',
        category: 'Main',
        mealType: 'Lunch',
        ingredients: [
          RecipeIngredient(quantity: 4, unit: 'oz', name: 'Ground Beef'),
          RecipeIngredient(quantity: 0.75, unit: 'cup', name: 'Brown Rice'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Guacamole'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Salsa'),
        ],
        totalCalories: 490,
        macros: Macros(protein: 28, carbs: 50, fat: 16),
      ),
      Recipe(
        id: 'seed_008',
        name: 'Turkey Wrap',
        category: 'Main',
        mealType: 'Lunch',
        ingredients: [
          RecipeIngredient(quantity: 1, unit: 'piece', name: 'Keto Wrap'),
          RecipeIngredient(quantity: 4, unit: 'oz', name: 'Turkey Breast'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Romaine Lettuce'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Hummus'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Cucumber'),
        ],
        totalCalories: 385,
        macros: Macros(protein: 30, carbs: 28, fat: 12),
      ),
      Recipe(
        id: 'seed_009',
        name: 'Turkey Salad',
        category: 'Main',
        mealType: 'Lunch',
        ingredients: [
          RecipeIngredient(quantity: 2, unit: 'cups', name: 'Mixed Greens'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Romaine Lettuce'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Cherry Tomato'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Cucumber'),
          RecipeIngredient(quantity: 4, unit: 'oz', name: 'Turkey Breast'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Dijon Dressing'),
        ],
        totalCalories: 285,
        macros: Macros(protein: 29, carbs: 13, fat: 12),
      ),
      Recipe(
        id: 'seed_010',
        name: 'Lemon Pepper Wings',
        category: 'Main',
        mealType: 'Dinner',
        ingredients: [
          RecipeIngredient(quantity: 6, unit: 'pieces', name: 'Wings'),
          RecipeIngredient(quantity: 1, unit: 'medium', name: 'Lemon'),
          RecipeIngredient(quantity: 2, unit: 'cups', name: 'Mixed Greens'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Romaine Lettuce'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Cherry Tomato'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Cucumber'),
          RecipeIngredient(quantity: 1, unit: 'tbsp', name: 'Raspberry Vinegar'),
        ],
        totalCalories: 425,
        macros: Macros(protein: 36, carbs: 9, fat: 26),
      ),
      Recipe(
        id: 'seed_011',
        name: 'Chicken Thigh W/Veg',
        category: 'Main',
        mealType: 'Dinner',
        ingredients: [
          RecipeIngredient(quantity: 5, unit: 'oz', name: 'Chicken Thigh'),
          RecipeIngredient(quantity: 1, unit: 'medium', name: 'Sweet Potato'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Green Beans'),
        ],
        totalCalories: 385,
        macros: Macros(protein: 31, carbs: 30, fat: 14),
      ),
      Recipe(
        id: 'seed_012',
        name: 'Shrimp Salad',
        category: 'Main',
        mealType: 'Lunch',
        ingredients: [
          RecipeIngredient(quantity: 5, unit: 'oz', name: 'Shrimp'),
          RecipeIngredient(quantity: 2, unit: 'cups', name: 'Mixed Greens'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Romaine Lettuce'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Cherry Tomato'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Cucumber'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Avocado'),
          RecipeIngredient(quantity: 1, unit: 'medium', name: 'Lemon'),
          RecipeIngredient(quantity: 1, unit: 'tbsp', name: 'Balsamic Vinegar'),
        ],
        totalCalories: 285,
        macros: Macros(protein: 27, carbs: 15, fat: 12),
      ),
      Recipe(
        id: 'seed_013',
        name: 'BBQ Chicken Wrap',
        category: 'Main',
        mealType: 'Lunch',
        ingredients: [
          RecipeIngredient(quantity: 1, unit: 'piece', name: 'Keto Wrap'),
          RecipeIngredient(quantity: 4, unit: 'oz', name: 'Chicken Breast'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Low Sugar BBQ'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Greek Yogurt'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Slaw Mix'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Red Onion'),
          RecipeIngredient(quantity: 2, unit: 'slices', name: 'Tomato'),
          RecipeIngredient(quantity: 1, unit: 'oz', name: 'Cheddar'),
        ],
        totalCalories: 430,
        macros: Macros(protein: 36, carbs: 33, fat: 14),
      ),
      Recipe(
        id: 'seed_014',
        name: 'Chicken Salad Wrap',
        category: 'Main',
        mealType: 'Lunch',
        ingredients: [
          RecipeIngredient(quantity: 4, unit: 'oz', name: 'Chicken'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Greek Yogurt'),
          RecipeIngredient(quantity: 1, unit: 'tsp', name: 'Mayo'),
          RecipeIngredient(quantity: 1, unit: 'tsp', name: 'Dijon'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Red Onion'),
          RecipeIngredient(quantity: 1, unit: 'tbsp', name: 'Relish'),
          RecipeIngredient(quantity: 1, unit: 'piece', name: 'Keto Wrap'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Romaine Lettuce'),
        ],
        totalCalories: 395,
        macros: Macros(protein: 33, carbs: 28, fat: 16),
      ),
      Recipe(
        id: 'seed_015',
        name: 'Ginger Turkey Rice',
        category: 'Main',
        mealType: 'Dinner',
        ingredients: [
          RecipeIngredient(quantity: 4, unit: 'oz', name: 'Ground Turkey'),
          RecipeIngredient(quantity: 0.75, unit: 'cup', name: 'Brown Rice'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Broccoli'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Carrots'),
          RecipeIngredient(quantity: 1, unit: 'tsp', name: 'Sesame Oil'),
          RecipeIngredient(quantity: 1, unit: 'tbsp', name: 'Soy Sauce'),
          RecipeIngredient(quantity: 1, unit: 'tsp', name: 'Honey'),
        ],
        totalCalories: 425,
        macros: Macros(protein: 29, carbs: 48, fat: 12),
      ),
      Recipe(
        id: 'seed_016',
        name: 'Turkey Spaghetti',
        category: 'Main',
        mealType: 'Dinner',
        ingredients: [
          RecipeIngredient(quantity: 1.5, unit: 'cups', name: 'Spaghetti Squash'),
          RecipeIngredient(quantity: 4, unit: 'oz', name: 'Ground Turkey'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Tomato Sauce'),
          RecipeIngredient(quantity: 1, unit: 'tsp', name: 'Olive Oil'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Onion'),
        ],
        totalCalories: 365,
        macros: Macros(protein: 29, carbs: 31, fat: 13),
      ),
      Recipe(
        id: 'seed_017',
        name: 'Chinese Coleslaw',
        category: 'Main',
        mealType: 'Lunch',
        ingredients: [
          RecipeIngredient(quantity: 2, unit: 'cups', name: 'Cabbage Mix'),
          RecipeIngredient(quantity: 0.25, unit: 'cup', name: 'Green Onion'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Cilantro'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Almonds'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Rice Vinegar'),
          RecipeIngredient(quantity: 1, unit: 'tbsp', name: 'Soy Sauce'),
          RecipeIngredient(quantity: 1, unit: 'tsp', name: 'Sesame Oil'),
          RecipeIngredient(quantity: 1, unit: 'tsp', name: 'Olive Oil'),
          RecipeIngredient(quantity: 1, unit: 'tsp', name: 'Stevia'),
          RecipeIngredient(quantity: 0.5, unit: 'tsp', name: 'Ginger'),
          RecipeIngredient(quantity: 1, unit: 'clove', name: 'Garlic'),
          RecipeIngredient(quantity: 1, unit: 'tsp', name: 'Sesame Seeds'),
        ],
        totalCalories: 185,
        macros: Macros(protein: 6, carbs: 17, fat: 11),
      ),
      Recipe(
        id: 'seed_018',
        name: 'Toms Cucumber Salad W/Chick',
        category: 'Main',
        mealType: 'Lunch',
        ingredients: [
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Cherry Tomato'),
          RecipeIngredient(quantity: 1, unit: 'medium', name: 'Cucumber'),
          RecipeIngredient(quantity: 1, unit: 'tbsp', name: 'Balsamic Vinegar'),
          RecipeIngredient(quantity: 2, unit: 'oz', name: 'Feta'),
          RecipeIngredient(quantity: 4, unit: 'oz', name: 'Chicken'),
        ],
        totalCalories: 285,
        macros: Macros(protein: 25, carbs: 13, fat: 13),
      ),
      Recipe(
        id: 'seed_019',
        name: 'Chicken Salad',
        category: 'Main',
        mealType: 'Lunch',
        ingredients: [
          RecipeIngredient(quantity: 2, unit: 'cups', name: 'Mixed Greens'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Romaine Lettuce'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Cherry Tomato'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Cucumber'),
          RecipeIngredient(quantity: 4, unit: 'oz', name: 'Chicken'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Dijon Dressing'),
        ],
        totalCalories: 265,
        macros: Macros(protein: 27, carbs: 11, fat: 12),
      ),
      Recipe(
        id: 'seed_020',
        name: 'Salmon W/Asparagus',
        category: 'Main',
        mealType: 'Dinner',
        ingredients: [
          RecipeIngredient(quantity: 5, unit: 'oz', name: 'Salmon'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Asparagus'),
          RecipeIngredient(quantity: 1, unit: 'tsp', name: 'Olive Oil'),
          RecipeIngredient(quantity: 1, unit: 'medium', name: 'Lemon'),
          RecipeIngredient(quantity: 2, unit: 'cloves', name: 'Garlic'),
        ],
        totalCalories: 380,
        macros: Macros(protein: 34, carbs: 9, fat: 22),
      ),
      Recipe(
        id: 'seed_021',
        name: 'Sweet Potato Turkey Bowl',
        category: 'Main',
        mealType: 'Dinner',
        ingredients: [
          RecipeIngredient(quantity: 4, unit: 'oz', name: 'Ground Turkey'),
          RecipeIngredient(quantity: 1, unit: 'medium', name: 'Sweet Potato'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Mixed Greens'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Avocado'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Salsa'),
        ],
        totalCalories: 420,
        macros: Macros(protein: 28, carbs: 42, fat: 14),
      ),
      Recipe(
        id: 'seed_022',
        name: 'Chick Pea Salad',
        category: 'Main',
        mealType: 'Lunch',
        ingredients: [
          RecipeIngredient(quantity: 0.75, unit: 'cup', name: 'Chick Pea'),
          RecipeIngredient(quantity: 2, unit: 'oz', name: 'Feta'),
          RecipeIngredient(quantity: 0.5, unit: 'medium', name: 'Cucumber'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Cherry Tomato'),
          RecipeIngredient(quantity: 2, unit: 'tbsp', name: 'Red Onion'),
          RecipeIngredient(quantity: 1, unit: 'tbsp', name: 'Balsamic Vinegar'),
          RecipeIngredient(quantity: 1, unit: 'tbsp', name: 'Cilantro'),
        ],
        totalCalories: 325,
        macros: Macros(protein: 13, carbs: 43, fat: 11),
      ),

      // ─── Snack ────────────────────────────────────────────────────────────
      Recipe(
        id: 'seed_023',
        name: 'Pudding',
        category: 'Snack',
        mealType: 'Snack',
        ingredients: [
          RecipeIngredient(quantity: 3, unit: 'tbsp', name: 'Chia Seeds'),
          RecipeIngredient(quantity: 1, unit: 'scoop', name: 'Protein Powder'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Almond Milk'),
        ],
        totalCalories: 225,
        macros: Macros(protein: 18, carbs: 16, fat: 9),
      ),
      Recipe(
        id: 'seed_024',
        name: 'Raspberry Pudding',
        category: 'Snack',
        mealType: 'Snack',
        ingredients: [
          RecipeIngredient(quantity: 3, unit: 'tbsp', name: 'Chia Seeds'),
          RecipeIngredient(quantity: 1, unit: 'cup', name: 'Almond Milk'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Raspberry'),
        ],
        totalCalories: 185,
        macros: Macros(protein: 5, carbs: 22, fat: 8),
      ),
      Recipe(
        id: 'seed_025',
        name: 'Almonds',
        category: 'Snack',
        mealType: 'Snack',
        ingredients: [
          RecipeIngredient(quantity: 1, unit: 'oz', name: 'Almonds'),
        ],
        totalCalories: 170,
        macros: Macros(protein: 6, carbs: 6, fat: 15),
      ),
      Recipe(
        id: 'seed_026',
        name: 'Hard Boiled Eggs',
        category: 'Snack',
        mealType: 'Snack',
        ingredients: [
          RecipeIngredient(quantity: 2, unit: 'large', name: 'Hard Boiled Eggs'),
        ],
        totalCalories: 140,
        macros: Macros(protein: 12, carbs: 1, fat: 10),
      ),
      Recipe(
        id: 'seed_027',
        name: 'Greek Yogurt W/Berries',
        category: 'Snack',
        mealType: 'Snack',
        ingredients: [
          RecipeIngredient(quantity: 0.75, unit: 'cup', name: 'Greek Yogurt'),
          RecipeIngredient(quantity: 0.5, unit: 'cup', name: 'Raspberry'),
          RecipeIngredient(quantity: 1, unit: 'tsp', name: 'Stevia'),
        ],
        totalCalories: 175,
        macros: Macros(protein: 14, carbs: 22, fat: 3),
      ),
    ];
  }
}
